AWSTemplateFormatVersion: "2010-09-09"

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: "retailco-api"
      ProtocolType: HTTP

  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: routes.handler
      Role: !GetAtt lambda.Arn
      Code:
        S3Bucket: !Ref WebsiteBucket
        S3Key: api/functions.zip
