name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - parallel:
          - name: build react app
            run: |
              npm ci
              npm run build

          - name: download api dependencies
            run: pip install -r api/requirements.txt -t api/

          - name: download agent dependencies
            run: pip install -r agent/requirements.txt -t agent/

          - name: Configure AWS
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.AWS_ROLE }}
              aws-region: us-east-1

      - parallel:
          - name: zip and push api code
            run: |
              cd api
              zip -q -r ../api.zip .
              cd ..
              aws s3 cp api.zip s3://retailco-api/api.zip

          - name: zip and push agent code
            run: |
              cd agent
              zip -q -r ../agent.zip .
              cd ..
              aws s3 cp agent.zip s3://retailco-api/agent.zip

          - name: Upload react app to S3
            run: |
              aws s3 sync out/ s3://retailco-web --delete

      - name: Run CloudFormation
        run: |
          aws cloudformation deploy \
          --template-file cloudformation.yml \
          --stack-name retailco \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
            OpenaiApiKey="${{ secrets.OPENAI_API_KEY }}"
